name: Deploy Skyporten-client

on:
  push:
    paths:
      - .nais/skyporten.yaml
      - .github/workflows/skyporten.yaml

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: .nais/skyporten.yaml
